# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V6AESiY-oVwz0supcOxIYz-bu3VEhstV

SPARKS FOUNDATION INTERNSHIP

Data Science and business analytics: Task 1
Prediction Using Supervised ML

Author: Yashaswini Gupta
"""

# Commented out IPython magic to ensure Python compatibility.
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

url="https://raw.githubusercontent.com/AdiPersonalWorks/Random/master/student_scores%20-%20student_scores.csv"
data=pd.read_csv(url)
data.head()

data.describe()

sns.scatterplot(x=data['Hours'], y=data['Scores']);

sns.regplot(x=data['Hours'], y=data['Scores']);

X = data[['Hours']]
y = data['Scores']

from sklearn.model_selection import train_test_split

train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)

from sklearn.linear_model import LinearRegression

regressor = LinearRegression()

regressor.fit(train_X, train_y)

pred_y = regressor.predict(val_X)

pd.DataFrame({'Actual': val_y, 'Predicted': pred_y})

h = [[9.25]]
s = regressor.predict(h)
print('A student who studies ', h[0][0] , ' predicted score is', s[0])